name: pc
version: '16.04-0.9'
type: gadget
summary: PC gadget for generic devices
description: |
    This gadget enables generic pc devices to work with Ubuntu Core
grade: stable
confinement: strict
icon: icon.png

parts:
  grub-prepare:
    plugin: nil
    stage-packages:
      - grub-efi-amd64-signed
      - grub-pc-bin
      - shim-signed
    prime: [ -* ]
  grub:
    source: .
    build-packages:
      - grub-common
    plugin: make
    after: [grub-prepare]
  recovery-configs:
    plugin: dump
    source: recovery-configs
    organize:
        devmode-firstboot-hooks/*: writable-includes/system-data/var/lib/devmode-firstboot/hooks.d/
        config.yaml: recovery-assets/recovery/
        grub_recovery.cfg: recovery-assets/EFI/ubuntu/grub.cfg
    stage:
        - -devmode-firstboot-hooks/
  ubuntu-custom-recovery:
    plugin: godeps
    source: https://github.com/Lyoncore/ubuntu-custom-recovery.git
    source-branch: master
    after:
      - recovery-configs
    go-importpath: github.com/Lyoncore/ubuntu-custom-recovery
    prepare: |
      snapcraft-hooks/prepare.sh
    build: |
      snapcraft-hooks/build.sh amd64
    install: |
      snapcraft-hooks/install.sh
    build-packages:
      - squashfs-tools
      - grub-common
      - gawk
      - sed
        
