project: generic-amd64
snaps:
  kernel: pc-kernel
  os: core
  gadget: pc
configs:
  arch: amd64
  baseimage: base.img
  bootsize: 512
  swap: on
  swapsize: 1024
  release: 16
  partition-type: gpt
  bootloader: grub
recovery:
  type: factory_install
  installerfslabel: INSTALLER
  recoverysize: 768
  filesystem-label: ESP
  oem-preinst-hook-dir: OEM_pre_install_hook
  oem-postinst-hook-dir: OEM_post_install_hook
  oem-prereboot-hook-dir: OEM_pre_reboot_hook
  oemlogdir: MFGMEDIA
